export enum NiveauActuel {
  BAC = 'BAC',
  PREPA1ER = 'PREPA1ER',
  PREPA2EME = 'PREPA2EME',
  LICENCE3EMEINFO = 'LICENCE3EMEINFO',
  LICENCE3EMENONINFO = 'LICENCE3EMENONINFO',
  MASTERE1ER = 'MASTERE1ER'
}
